# axis_linear:
#   x: 1
#   y: 0
# scale_linear:
#   x: 0.5
#   y: 0.5
# scale_linear_turbo:
#   x: 1.6
#   y: 1.6
# axis_angular:
#   yaw: 3
# scale_angular:
#   yaw: 0.8
# scale_angular_turbo:
#   yaw: 1.2

axis_position_map: 
  x: 1
  y: 0
  z: 4
  w: 3

axis_orientation_map:
  x: 1
  y: 0
  z: 4
  w: 3

position_max_displacement_in_a_second: 1 #cambiar por max displacement in a second
orientation_max_displacement_in_a_second: 1 #mov angular


change_z_button: 0
enable_mov_position: 4
enable_mov_orientation: 5
orientation_button: 9
home_button: 8
increment_velocity: 6
decrement_velocity: 7
