# Configuracion del mapeo de ejes y botones para el paquete de ROS

# Axis mapping

axis_position_map: # control de posicion
  x: 1
  y: 0
  z: 4

axis_orientation_map: # control de orientacion
  x: 0
  y: 1
  z: 4

# Button mapping
change_z_button: 0
enable_mov_position: 4
enable_mov_orientation: 5
orientation_button: 9
home_button: 8
increment_velocity: 6
decrement_velocity: 7

# Parametros
position_max_displacement_in_a_second: 12.5
orientation_max_displacement_in_a_second: 50
