# axis_linear:
#   x: 1
#   y: 0
# scale_linear:
#   x: 0.5
#   y: 0.5
# scale_linear_turbo:
#   x: 1.6
#   y: 1.6
# axis_angular:
#   yaw: 3
# scale_angular:
#   yaw: 0.8
# scale_angular_turbo:
#   yaw: 1.2

JL:
  x: 1
  y: 0
  z: 4
scale_JL: # range of movement
  x: 0.5
  y: 0.5
  z: 0.5
scale_JL_turbo:
  x: 1
  y: 1
  z: 1

change_z_button: 0
enable_button: 4
enable_turbo_button: 5
orientation_button: 9
home_button: 8
