# axis_linear:
#   x: 1
#   y: 0
# scale_linear:
#   x: 0.5
#   y: 0.5
# scale_linear_turbo:
#   x: 1.6
#   y: 1.6
# axis_angular:
#   yaw: 3
# scale_angular:
#   yaw: 0.8
# scale_angular_turbo:
#   yaw: 1.2

JL: 
  x: 1
  y: 0
  z: 4
  w: 3

position_max_displacement_in_a_second: #cambiar por max displacement in a second
  x: 10
  y: 10
  z: 10
orientation_max_displacement_in_a_second: #mov angular
  x: 10
  y: 10
  z: 10
  w: 10


change_z_button: 0
enable_mov_position: 4
enable_mov_orientation: 5
orientation_button: 9
home_button: 8
increment_velocity: 6
decrement_velocity: 7
