# axis_linear:
#   x: 1
#   y: 0
# scale_linear:
#   x: 0.5
#   y: 0.5
# scale_linear_turbo:
#   x: 1.6
#   y: 1.6
# axis_angular:
#   yaw: 3
# scale_angular:
#   yaw: 0.8
# scale_angular_turbo:
#   yaw: 1.2

JL:
  x: 1
  y: 
scale_JL: # range of movement
  x: 1
  y: 1
scale_JL_turbo:
  x: 10
  y: 10
enable_button: 4
enable_turbo_button: 5
